spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 10000 # 10s
      request-read-timeout: 10000 # 10s
      # The retry behavior is enabled only when this property is set to true
      fail-fast: false # In production set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 # ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        # OAuth2 doesn't enforce a data format for Access Tokens, so we must
        # be explicit about our choice. In this case, we want to use JWT.
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

polar:
  greeting: Welcome to the local book catalog!