apiVersion: v1
kind: Service
metadata:
  name: catalogservice
  labels:
    app: catalogservice
spec:
  type: ClusterIP
  selector:
    app: catalogservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
